
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432

development:
  <<: *default
  database: hospital_app_dev
  host: localhost
  username: postgres
  password: root

test:
  <<: *default
  database: hospital_app_test
  host: localhost
  username: postgres
  password: root
 # database: hospital_app_test

production:
  <<: *default
 # database: hospital_app_production
  #username: hospital_app
 # password: <%= ENV["HOSPITAL_APP_DATABASE_PASSWORD"] %>
